spring:
  application:
    name: batch-study
  # H2 Database
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_user}
    password: ${db_password}
